#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# hochitom.rocks goes live (ticket .scratch/pin-katalog/issues/11-online-gehen.md).
# Already in place before this wizard: the public repo hochitom/rocks with `main` pushed,
# the Netlify site "hochitomrocks" (still building the old `master`), DNS at domaintechnik.at
# pointing to Netlify. This wizard switches everything over to the new Astro site.
# Run it from the repository root: bash scripts/go-live.sh

REPO="hochitom/rocks"
NETLIFY_SITE="hochitomrocks"
NETLIFY="https://app.netlify.com/sites/$NETLIFY_SITE"
NETLIFY_IP="75.2.60.5"

TOTAL_STAGES=7

banner "hochitom.rocks goes live"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "GitHub: push the latest main"
say "Netlify builds whatever is on GitHub's main, so the newest commits go up first."
note "Local main: $(git log -1 --format='%h %s' main)"
note "GitHub main: $(git ls-remote origin refs/heads/main | cut -c1-7)"
if confirm "Push main to origin now?"; then
  git push origin main
else
  SKIPPED+=("git push origin main")
  warn "not pushed; Netlify will build the older main"
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Netlify: build main instead of the old master"
say "The site $NETLIFY_SITE still deploys the old master branch. Point it at main."
open_url "$NETLIFY/configuration/deploys"
step "Section 'Continuous deployment' → 'Repository': it must say github.com/$REPO."
note "If no repository is linked: 'Link repository' → GitHub → $REPO."
step "'Branches and deploy contexts' → 'Configure' → Production branch: main → Save."
step "'Build settings' → 'Configure': leave Build command and Publish directory empty"
note "(netlify.toml in the repo sets: npm run build → dist, Node 24). Save."
note "If the Netlify UI looks different: the same settings live under Project configuration → Build & deploy."
pause "Done in Netlify? Press Enter"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: Web Analytics token (optional)"
say "Cloudflare Web Analytics counts visits without cookies. Without it, Netlify's own request statistics remain."
note "Switched off for now (2026-10-06). Answer no to keep it off; the privacy section adapts automatically."
CLOUDFLARE_ANALYTICS_TOKEN=""
if confirm "Switch on Cloudflare Web Analytics?"; then
open_url "https://dash.cloudflare.com/?to=/:account/web-analytics"
step "Log in, then 'Add a site' → Hostname: hochitom.rocks → Done."
note "Don't choose automatic setup via Cloudflare DNS: the DNS stays at domaintechnik.at."
step "Cloudflare shows a JS snippet. Copy only the token from data-cf-beacon='{\"token\": \"…\"}'."
note "Already added earlier? Web Analytics → hochitom.rocks → 'Manage site' shows the snippet again."
while [[ -z "$CLOUDFLARE_ANALYTICS_TOKEN" ]]; do
  ask CLOUDFLARE_ANALYTICS_TOKEN "Paste the token (32 characters):"
done
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Netlify: analytics token and deploy of the new site"
if [[ -n "$CLOUDFLARE_ANALYTICS_TOKEN" ]]; then
  say "The build adds the analytics script only when this variable is set."
  open_url "$NETLIFY/configuration/env"
  step "'Add a variable' → 'Add a single variable'."
  step "Key: CLOUDFLARE_ANALYTICS_TOKEN"
  step "Value: $CLOUDFLARE_ANALYTICS_TOKEN"
  step "Scopes: at least 'Builds'. Deploy contexts: Production (all is fine too) → Create variable."
  pause "Variable saved? Press Enter"
else
  say "No analytics: make sure CLOUDFLARE_ANALYTICS_TOKEN is not set in Netlify."
fi
open_url "$NETLIFY/deploys"
step "'Trigger deploy' → 'Clear cache and deploy site'."
note "The build takes about a minute. If it fails, open the deploy log and copy the first error."
pause "Deploy started? Press Enter"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Check: the new site is live"
say "Waiting until https://hochitom.rocks serves the Astro site with the analytics beacon."
live=""
for _ in $(seq 1 40); do
  html=$(curl -fsS -m 15 "https://hochitom.rocks/" 2>/dev/null || true)
  if [[ "$html" == *"/_astro/"* ]]; then live="yes"; break; fi
  printf '  %s… not yet, checking again in 15 s%s\n' "$DIM" "$RESET"
  sleep 15
done
if [[ -n "$live" ]]; then
  printf '  %s✓ the new site is live%s\n' "$GREEN" "$RESET"
  if [[ -z "$CLOUDFLARE_ANALYTICS_TOKEN" ]]; then
    note "analytics switched off, no beacon expected"
  elif [[ "$html" == *"cloudflareinsights.com/beacon.min.js"* && "$html" == *"$CLOUDFLARE_ANALYTICS_TOKEN"* ]]; then
    printf '  %s✓ analytics beacon with your token is on the page%s\n' "$GREEN" "$RESET"
  else
    warn "the analytics beacon is missing: check the variable from stage 4 and redeploy"
    SKIPPED+=("Analytics beacon: check CLOUDFLARE_ANALYTICS_TOKEN in Netlify, then 'Clear cache and deploy site'")
  fi
else
  warn "after 10 minutes the old site is still served: check the deploy log in Netlify"
  SKIPPED+=("New site not live yet: check $NETLIFY/deploys")
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Domain and HTTPS"
say "The DNS at domaintechnik.at should already point to Netlify. Checking:"
apex=$(dig +short hochitom.rocks A | tr '\n' ' ')
www=$(dig +short www.hochitom.rocks CNAME | tr '\n' ' ')
note "hochitom.rocks A      → ${apex:-nothing}   (expected $NETLIFY_IP)"
note "www.hochitom.rocks    → ${www:-nothing}   (expected $NETLIFY_SITE.netlify.app.)"
if [[ "$apex" != "$NETLIFY_IP " || "$www" != "$NETLIFY_SITE.netlify.app. " ]]; then
  warn "DNS differs. In the domaintechnik.at customer area, DNS settings for hochitom.rocks:"
  step "A record for the main domain (@) → $NETLIFY_IP; remove other A/AAAA records of @."
  step "CNAME for www → $NETLIFY_SITE.netlify.app"
  note "Changes can take up to a few hours to show."
  SKIPPED+=("DNS: A @ → $NETLIFY_IP, CNAME www → $NETLIFY_SITE.netlify.app")
fi
if curl -fsS -m 15 -o /dev/null "https://hochitom.rocks/"; then
  printf '  %s✓ https://hochitom.rocks answers with a valid certificate%s\n' "$GREEN" "$RESET"
else
  warn "HTTPS doesn't work yet"
  SKIPPED+=("HTTPS: $NETLIFY/configuration/domain → HTTPS → 'Verify DNS configuration' / 'Provision certificate'")
fi
www_to=$(curl -sS -m 15 -o /dev/null -w '%{http_code} %{redirect_url}' "https://www.hochitom.rocks/" || true)
note "www.hochitom.rocks → $www_to (expected 301 to https://hochitom.rocks/)"
open_url "$NETLIFY/configuration/domain"
step "Check: hochitom.rocks is the primary domain, www redirects to it, HTTPS shows a certificate."
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "GitHub: archive the old master"
say "The old site on master is kept as tag old-site; then main becomes the only branch."
note "Do this only after stage 5 showed the new site live, so Netlify no longer needs master."
if confirm "Tag master as old-site, make main the default branch and delete master on GitHub?"; then
  git fetch origin master
  git tag -f old-site origin/master
  git push origin refs/tags/old-site
  gh repo edit "$REPO" --default-branch main
  git push origin --delete master
  git remote set-head origin main
  printf '  %s✓ master archived as tag old-site, main is the default branch%s\n' "$GREEN" "$RESET"
else
  SKIPPED+=("Archive master: git tag old-site origin/master, push tag, gh repo edit $REPO --default-branch main, git push origin --delete master")
fi
pause

finish
say "Ticket 11 can be ticked off. Open https://hochitom.rocks on your phone to check the 3D pin and the globe."
printf '\n'
